<?php

namespace AppBundle\Repository;

/**
 * ticketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ticketRepository extends \Doctrine\ORM\EntityRepository
{
}
